---
output: html_document
params: 
   point_data : NULL
   next_link  : NULL
---

```{r}
htmltools::h1(params$point_data$point, class = "title")
```

```{r setup, include=FALSE}
leaf_plot <- function(dt, year){
  wms <- sprintf("https://services.nconemap.gov/secure/services/Imagery/Orthoimagery_%s/ImageServer/WMSServer", year)
  leaflet() %>% 
    setView(lng = dt$lon, lat = dt$lat, zoom = 18) %>% 
    # addTiles() %>%
    addWMSTiles(
      wms, layers = "0",
      options = WMSTileOptions(format = "image/png",  version = "1.3.0",
                               crs = leafletCRS("L.CRS.EPSG4326"))
    ) %>%
    addMarkers(
      data = dt,
      icon = icons(
        iconUrl = "mapicon.png",
        iconWidth = 20, iconHeight = 20,
        iconAnchorX = 10, iconAnchorY = 10))
}

make_plot <- function(dt){
  latticeview(
    leaf_plot(dt, "2008"), 
    leaf_plot(dt, "2017")
  )
}
```

```{r, message=FALSE}
make_plot(params$point_data)
```


<iframe id="googleform" src="" width="300" height="540" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

```{js}
	var point = document.getElementsByTagName("h1")[0].innerText;
	var googlesrc = 'https://docs.google.com/forms/d/e/1FAIpQLSd75sB2uL5LvNHyaLiIPNM7dkVU2klLBBFn8AxP5cfSMHXU-Q/viewform?usp=pp_url&entry.900066253='+point+'&embedded=true';
	document.getElementById("googleform").src = googlesrc;
```


```{r, results='asis'}
if(!is.null(params$next_link)){
  htmltools::a(href = params$next_link, "Next point")
}
```